name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # 允许手动触发工作流

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      # 设置MySQL服务用于测试
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: toolcat_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 --silent; then
              break
            fi
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Create test database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p123456 -e "CREATE DATABASE IF NOT EXISTS toolcat_test;"

      - name: Set up test environment variables
        run: |
          echo "TEST_DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "TEST_DB_PORT=3306" >> $GITHUB_ENV
          echo "TEST_DB_USERNAME=root" >> $GITHUB_ENV
          echo "TEST_DB_PASSWORD=123456" >> $GITHUB_ENV
          echo "TEST_DB_NAME=toolcat_test" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_USERNAME=root" >> $GITHUB_ENV
          echo "DB_PASSWORD=123456" >> $GITHUB_ENV
          echo "DB_NAME=toolcat_test" >> $GITHUB_ENV

      - name: Run unit tests
        run: go test -v ./test/models/... ./test/pkg/... ./test/middleware/...

      - name: Run integration tests
        run: go test -v ./test/controllers/... ./test/routers/... ./test/plugins/...

      - name: Run all tests
        run: go test -v ./test/...



  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build -v -o toolcat main.go



  deploy:
    name: Deploy (Main Branch Only)
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Notify deployment
        run: echo "Deployment would happen here for commit ${{ github.sha }}"